(in-package #:dds.tests)

;;; Exercise the type compiler (FR-TOOL-1): define a type from the s-expr DSL,
;;; then round-trip it through the GENERATED codec and the registered type-support
;;; vtable. gsample's i64 follows an i32, exercising the XCDR2 alignment path.

(dds.gen:define-dds-type gsample (:extensibility :final)
  (id :i32 :key t)
  (ts :i64)
  (label :string))

(declaim (ftype (function () t) run-generated-type-test))
(defun run-generated-type-test ()
  (let* ((arena (dds.core.arena:init-arena :bytes (* 64 1024)))
         (pool (dds.core.arena:make-buffer-pool arena 512 2))
         (s (make-gsample :id -42 :ts 9999999999 :label "gen")))
    (flet ((rt (mode)
             (let* ((b (dds.core.arena:pool-acquire pool))
                    (wc (dds.core.buffer:cursor b :endianness :little)))
               (serialize-gsample s wc mode)
               (let ((wrote (dds.core.buffer:cursor-position wc))
                     (rc (dds.core.buffer:cursor b :endianness :little)))
                 (let ((q (deserialize-gsample rc mode)))
                   (dds.core.arena:pool-release pool b)
                   (values q wrote))))))
      (multiple-value-bind (q1 len1) (rt :xcdr2)
        (%check :gen-roundtrip
                (and (= (gsample-id q1) -42)
                     (= (gsample-ts q1) 9999999999)
                     (string= (gsample-label q1) "gen"))
                "generated XCDR2 round-trip mismatch")
        (%check :gen-size
                (= len1 (serialized-size-gsample s :xcdr2))
                (format nil "serialized-size ~d != bytes written ~d"
                        (serialized-size-gsample s :xcdr2) len1)))
      ;; type-support registered and usable purely through the vtable
      (let ((ts (dds.types:find-type-support "gsample")))
        (%check :gen-registered (and ts (dds.types:type-support-p ts))
                "type-support not registered")
        (let* ((b (dds.core.arena:pool-acquire pool))
               (wc (dds.core.buffer:cursor b :endianness :little)))
          (funcall (dds.types:type-support-serialize ts) s wc :xcdr2)
          (let* ((rc (dds.core.buffer:cursor b :endianness :little))
                 (q (funcall (dds.types:type-support-deserialize ts) rc :xcdr2)))
            (%check :gen-vtable (string= "gen" (gsample-label q))
                    "type-support vtable round-trip failed"))
          (dds.core.arena:pool-release pool b)))
      (dds.core.arena:teardown-arena arena)
      t)))

(dds.gen:define-dds-type gseq (:extensibility :final)
  (n :u16)
  (vals (:sequence :i32))
  (tag :string))

(declaim (ftype (function () t) run-generated-sequence-test))
(defun run-generated-sequence-test ()
  (let* ((arena (dds.core.arena:init-arena :bytes (* 64 1024)))
         (pool (dds.core.arena:make-buffer-pool arena 512 1))
         (s (make-gseq :n 3 :vals #(10 -20 30) :tag "seq")))
    (let* ((b (dds.core.arena:pool-acquire pool))
           (wc (dds.core.buffer:cursor b :endianness :little)))
      (serialize-gseq s wc :xcdr2)
      (let* ((wrote (dds.core.buffer:cursor-position wc))
             (rc (dds.core.buffer:cursor b :endianness :little))
             (q (deserialize-gseq rc :xcdr2)))
        (%check :gseq-roundtrip
                (and (= (gseq-n q) 3)
                     (equalp (gseq-vals q) #(10 -20 30))
                     (string= (gseq-tag q) "seq"))
                "generated sequence round-trip mismatch")
        (%check :gseq-size (= wrote (serialized-size-gseq s :xcdr2))
                (format nil "seq serialized-size ~d != bytes written ~d"
                        (serialized-size-gseq s :xcdr2) wrote))
        (dds.core.arena:pool-release pool b)))
    (dds.core.arena:teardown-arena arena)
    t))

(dds.gen:define-dds-type gpoint (:extensibility :final)
  (x :i32)
  (y :i32))

(dds.gen:define-dds-type gseg (:extensibility :final)
  (a gpoint)
  (b gpoint)
  (tag :string))

(declaim (ftype (function () t) run-generated-nested-test))
(defun run-generated-nested-test ()
  (let* ((arena (dds.core.arena:init-arena :bytes (* 64 1024)))
         (pool (dds.core.arena:make-buffer-pool arena 512 1))
         (s (make-gseg :a (make-gpoint :x 1 :y 2)
                       :b (make-gpoint :x -3 :y 4)
                       :tag "seg")))
    (let* ((buf (dds.core.arena:pool-acquire pool))
           (wc (dds.core.buffer:cursor buf :endianness :little)))
      (serialize-gseg s wc :xcdr2)
      (let* ((wrote (dds.core.buffer:cursor-position wc))
             (rc (dds.core.buffer:cursor buf :endianness :little))
             (q (deserialize-gseg rc :xcdr2)))
        (%check :gseg-nested-roundtrip
                (and (= (gpoint-x (gseg-a q)) 1) (= (gpoint-y (gseg-a q)) 2)
                     (= (gpoint-x (gseg-b q)) -3) (= (gpoint-y (gseg-b q)) 4)
                     (string= (gseg-tag q) "seg"))
                "generated nested round-trip mismatch")
        (%check :gseg-nested-size (= wrote (serialized-size-gseg s :xcdr2))
                (format nil "nested serialized-size ~d != bytes written ~d"
                        (serialized-size-gseg s :xcdr2) wrote))
        (dds.core.arena:pool-release pool buf)))
    (dds.core.arena:teardown-arena arena)
    t))

;;; Pooled zero-alloc deserialize (NFR-PERF-8). mpoint/mline are fully fixed-size
;;; (no strings/sequences), so deserialize-into-mline fills a loaned struct in
;;; place with no per-sample allocation.

(dds.gen:define-dds-type mpoint (:extensibility :final)
  (x :i32)
  (y :i32))

(dds.gen:define-dds-type mline (:extensibility :final)
  (a mpoint)
  (b mpoint)
  (n :i32))

(declaim (ftype (function () t) run-generated-into-test))
(defun run-generated-into-test ()
  (let* ((arena (dds.core.arena:init-arena :bytes (* 64 1024)))
         (pool (dds.core.arena:make-buffer-pool arena 512 1))
         (ts (dds.types:find-type-support "mline"))
         (src (make-mline :a (make-mpoint :x 1 :y 2) :b (make-mpoint :x 3 :y 4) :n 5))
         (sample (funcall (dds.types:type-support-sample-pool-alloc ts))))
    (%check :into-loan (and sample (mline-p sample)) "sample-pool-alloc returned non-sample")
    (let* ((buf (dds.core.arena:pool-acquire pool))
           (wc (dds.core.buffer:cursor buf :endianness :little)))
      (serialize-mline src wc :xcdr2)
      (let ((rc (dds.core.buffer:cursor buf :endianness :little)))
        (deserialize-into-mline sample rc :xcdr2))
      (%check :into-roundtrip
              (and (= (mpoint-x (mline-a sample)) 1) (= (mpoint-y (mline-a sample)) 2)
                   (= (mpoint-x (mline-b sample)) 3) (= (mpoint-y (mline-b sample)) 4)
                   (= (mline-n sample) 5))
              "deserialize-into round-trip mismatch")
      (dds.core.arena:pool-release pool buf))
    (funcall (dds.types:type-support-sample-pool-free ts) sample)
    (dds.core.arena:teardown-arena arena)
    t))

(declaim (ftype (function () t) run-mem-test))
(defun run-mem-test ()
  "Measured zero-alloc serialize + deserialize (NFR-PERF-8). Asserted on SBCL
   (exact bytes-consed); on Clasp bytes-consed is 0 (gap) so it only smokes."
  (let* ((arena (dds.core.arena:init-arena :bytes (* 64 1024)))
         (pool (dds.core.arena:make-buffer-pool arena 512 1))
         (ts (dds.types:find-type-support "mline"))
         (src (make-mline :a (make-mpoint :x 7 :y 8) :b (make-mpoint :x 9 :y 10) :n 11))
         (sample (funcall (dds.types:type-support-sample-pool-alloc ts)))
         (buf (dds.core.arena:pool-acquire pool))
         (wc (dds.core.buffer:cursor buf :endianness :little))
         (rc (dds.core.buffer:cursor buf :endianness :little))
         (iters 100000))
    (serialize-mline src wc :xcdr2)
    (deserialize-into-mline sample rc :xcdr2)         ; warm up both paths
    (flet ((measure (label thunk)
             (declare (type function thunk))
             (let ((before (dds.pal:bytes-consed)))
               (dotimes (i iters) (funcall thunk))
               (let* ((delta (- (dds.pal:bytes-consed) before))
                      (per (/ (float delta) iters)))
                 (format t "~&  mem[~11a]: ~9d bytes / ~d iters = ~,4f bytes/sample (~a)~%"
                         label delta iters per (dds.pal:pal-impl-name))
                 (when (eq (dds.pal:pal-impl-name) :sbcl)
                   (%check :zero-alloc (< per 1.0)
                           (format nil "~a: ~,4f bytes/sample (expected ~~0)" label per)))))))
      (measure "serialize"
               (lambda () (dds.core.buffer:cursor-reset wc) (serialize-mline src wc :xcdr2)))
      (measure "deserialize"
               (lambda () (dds.core.buffer:cursor-reset rc) (deserialize-into-mline sample rc :xcdr2)))
      (measure "round-trip"
               (lambda ()
                 (dds.core.buffer:cursor-reset wc) (serialize-mline src wc :xcdr2)
                 (dds.core.buffer:cursor-reset rc) (deserialize-into-mline sample rc :xcdr2))))
    (funcall (dds.types:type-support-sample-pool-free ts) sample)
    (dds.core.arena:pool-release pool buf)
    (dds.core.arena:teardown-arena arena)
    t))
